apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-{{ task_instance.task_id }}
  namespace: spark-operator
spec:
  type: Scala
  mode: cluster
  image: spark:3.5.3
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples.jar
  arguments:
    - "1000"
  sparkVersion: 3.5.3
  timeToLiveSeconds: 3600  # Podden lever i 1 timme efter avslutning
  sparkConf:
    "spark.kubernetes.executor.label.applicationId": spark-pi-{{ task_instance.task_id }}
    "spark.kubernetes.driver.label.applicationId": spark-pi-{{ task_instance.task_id }}
    "spark.kubernetes.executor.label.queue": "default.root.elias"
    "spark.kubernetes.driver.label.queue": default.root.elias"
  driver:
    labels:
      version: 3.5.3
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    labels:
      version: 3.5.3
    instances: 1
    cores: 1
    memory: 512m
  batchScheduler: yunikorn
  batchSchedulerOptions:
    queue: default.root.elias
