apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-python-app-k8s
  namespace: spark-operator
spec:
  type: Python
  mode: cluster
  image: harbor.ad.spendrups.se/dataplatform-test/spark-kafka-to-base:1.0
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/sparkKafkaToBase.py  # Placera din Python-fil i /app
  sparkVersion: 3.5.3
  timeToLiveSeconds: 3600  # Podden lever i 1 timme efter avslutning
  sparkConf:
    "spark.executor.memoryOverhead": "256m"
    "spark.kubernetes.container.image.pullPolicy": "IfNotPresent"
  driver:
    labels:
      version: 3.5.3
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    labels:
      version: 3.5.3
    instances: 2
    cores: 1
    memory: 512m
